# version: '3.8' # Version autodetect in Docker v2.35.1
volumes:
    prometheus_data:
      driver: local
      driver_opts:
        type: none
        device: ~/prom/prometheus/prometheus_data
        o: bind
    grafana_data:
      driver: local
      driver_opts:
        type: none
        device: ~/prom/grafana/grafana_data
        o: bind
    alertmanager_data:
      driver: local
      driver_opts:
        type: none
        device: ~/prom/alertmanager/alertmanager_data
        o: bind

networks:
  front-tier:
  back-tier:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:

# Prometheos
  prometheus:
    user: "655534:655534" # UID Prometheos
    image: prom/prometheus:v3.3.0 # Fix version 2025.04.21
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    links:
      - alertmanager:alertmanager
      - pushgateway:pushgateway
    depends_on:
      - pushgateway
    networks:
      - back-tier
    restart: always
    environment:
      TZ: "Europe/Moscow"

# Alertmanager
  alertmanager:
    user: "65534:65534" # UID Alertmanager
    image: prom/alertmanager:v0.28.1 # Fix version 2025.04.21
    ports:
      - "9093:9093"
    volumes:
      - alertmanager_data:/alertmanager
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - back-tier
    environment:
      TZ: "Europe/Moscow"
    restart: unless-stopped

# Grafana
  grafana:
    image: grafana/grafana:11.6.0 # Fix version 2025.04.21
    user: "472:472" # UID Grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ~/prom/grafana/config/custom.ini:/etc/grafana/custom.ini  # Mounting the file custome.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

# Pushgateway
  pushgateway:
    image: prom/pushgateway:v1.11.1 # Fix version 2025.04.21
    ports:
      - "9091:9091"
    networks:
      - back-tier
    restart: on-failure
